# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  # push:
  #   branches: [main, master]
  # Allow a manual run of the workflow
  workflow_dispatch:

name: test-coverage-gist.yaml

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            type = "tests",  # unit tests only
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
          pkg_cov <- covr::percent_coverage(cov)
          Sys.setenv(COVERAGE = pkg_cov)
          if (pkg_cov > 75) {
            Sys.setenv(COVERAGE_COLOR = "green")  
          } else if (pkg_cov > 50) {
            Sys.setenv(COVERAGE_COLOR = "yellow")  
          } else {
            Sys.setenv(COVERAGE_COLOR = "red")  
          }
        shell: Rscript {0}

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: d1c44251dc166a6148015f7414a0ed1a
          filename: gstest_coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}
          color: ${{ env.COVERAGE_COLOR }}
          #namedLogo: jest
          #logoColor: lightblue

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
